# Generated by Django 4.2.7 on 2024-11-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
