# Generated by Django 4.2.7 on 2024-11-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
