# Generated by Django 4.2.7 on 2024-11-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_contact_added_on_contact_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha añadido'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.status', verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha actualizado'),
        ),
    ]
