# Generated by Django 4.2.7 on 2024-12-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_companysector_alter_contact_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.AlterModelOptions(
            name='companysector',
            options={'verbose_name': 'Sector de empresa', 'verbose_name_plural': 'Sectores de empresas'},
        ),
    ]
