# Generated by Django 4.2.7 on 2024-12-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_features_alter_companysector_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de residencial',
                'verbose_name_plural': 'Tipos de residenciales',
            },
        ),
    ]
