# Generated by Django 4.2.7 on 2024-12-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_residentialtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Empleados de empresa',
                'verbose_name_plural': 'Empleados de empresas',
            },
        ),
        migrations.AlterModelOptions(
            name='residentialtype',
            options={'verbose_name': 'Tipo de residencia', 'verbose_name_plural': 'Tipos de residencias'},
        ),
        migrations.CreateModel(
            name='QuoteResidential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='fecha añadido')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='fecha actualizado')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.contact', verbose_name='contacto')),
                ('features', models.ManyToManyField(to='leads.features', verbose_name='características')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.status', verbose_name='estado')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.residentialtype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Cotización de residencia',
                'verbose_name_plural': 'Cotizaciones de residencias',
            },
        ),
        migrations.CreateModel(
            name='QuoteCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='fecha añadido')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='fecha actualizado')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.contact', verbose_name='contacto')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.companyemployees', verbose_name='empleados')),
                ('features', models.ManyToManyField(to='leads.features', verbose_name='características')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.companysector', verbose_name='sector')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.status', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Cotización de empresa',
                'verbose_name_plural': 'Cotizaciones de empresas',
            },
        ),
    ]
