# Generated by Django 4.2.7 on 2024-12-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_companyemployees_alter_residentialtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinotoringUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Usuario que monitorea',
                'verbose_name_plural': 'Usuarios que monitorean',
            },
        ),
        migrations.CreateModel(
            name='MonitoringTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Objetivo de monitoreo',
                'verbose_name_plural': 'Objetivos de monitoreo',
            },
        ),
        migrations.AddField(
            model_name='quotecompany',
            name='branches',
            field=models.IntegerField(default=1, verbose_name='sucursales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotecompany',
            name='has_wifi',
            field=models.BooleanField(default=1, verbose_name='tiene wifi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteresidential',
            name='has_wifi',
            field=models.BooleanField(default=1, verbose_name='tiene wifi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoteresidential',
            name='rooms',
            field=models.IntegerField(default=1, verbose_name='habitaciones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotecompany',
            name='users',
            field=models.ManyToManyField(to='leads.minotoringuser', verbose_name='usuarios'),
        ),
        migrations.AddField(
            model_name='quoteresidential',
            name='targets',
            field=models.ManyToManyField(to='leads.monitoringtarget', verbose_name='objetivos'),
        ),
    ]
