# Generated by Django 4.2.7 on 2025-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_rename_minotoringuser_monitoringuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotecompany',
            name='has_cameras',
            field=models.BooleanField(default=False, verbose_name='tiene cámaras'),
        ),
        migrations.AddField(
            model_name='quoteresidential',
            name='has_cameras',
            field=models.BooleanField(default=False, verbose_name='tiene cámaras'),
        ),
    ]
